# Dependencies

#markdown: kramdown
#kramdown: 
#  input: GFM
#  toc_levels: 1..2
  # parse_block_html: true

# markdown: CommonMarkGhPages

highlighter:      rouge

# Permalinks
# permalink:        pretty

# Setup
title:            "Pello Aspuru"
tagline:          'CEMFI'
description:      'PhD candidate, CEMFI'
url:              https://pelloaspuru.github.io
baseurl:          ''

# For changing favicon.
authorimage = "/photos/favicon_lemon.ico"

author:
  name:           'Pello Aspuru'

paginate:         10
paginate_path:    "/blog/page:num/"

# Custom vars
# version:          2.1.0

github:           
  repo:           https://github.com/pelloaspuru/pelloaspuru.github.io

plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-commonmark-ghpages

disqus:
  shortname: pelloaspuru
