# Dependencies

#markdown: kramdown
#kramdown: 
#  input: GFM
#  toc_levels: 1..2
  # parse_block_html: true

# markdown: CommonMarkGhPages

highlighter:      rouge

# Permalinks
# permalink:        pretty

# Setup
title:            "Pello Aspuru"
tagline:          'Vienna'
description:      'Assistant Professor'
url:              https://pelloaspuru.github.io
baseurl:          ''

# For changing favicon (does not work)
# authorimage = "/photos/favicon_lemon.ico"

author:
  name:           'Pello Aspuru'

paginate:         10
paginate_path:    "/blog/page:num/"

# Custom vars
# version:          2.1.0

github:           
  repo:           https://github.com/pelloaspuru/pelloaspuru.github.io

plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-commonmark-ghpages

disqus:
  shortname: pelloaspuru
  
# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      classes: "wide"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"
      classes: "wide"
      
